sudo: false
language: python
python:
- '3.7'
before_install:
  - pip install poetry
install:
  - poetry install -v
script:
  - poetry run pytest -s
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
